### ISSUE TITLE
Katya Asset

### ISSUE THREAD

**Issue by mayaholeman** [mayaholeman/FutureWorld#6]
**Is your feature request related to a problem? Please describe.**
Need to create the base mechanics of the Player Character Katya.

**Describe the solution you'd like**
Create Katya Asset. Include the ability to move, shoot one weapon of choice, and take damage.

**Additional context**
Use one of the following models:
- https://assetstore.unity.com/packages/3d/characters/humanoids/sci-fi-engineer-29165
- https://assetstore.unity.com/packages/3d/characters/humanoids/sci-fi-cyborg-girl-35921

**Comment by mayaholeman** [comment]
Make the Actions for Katya state-based instead of on call.

**Comment by ghost** [comment]
On branch 6KatyaAsset
